### ISSUE TITLE
did you moved the package?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.carousel#2]
I think you forgot to update the references of collective.carousel in http://plone.org/products/collective.carousel and http://pypi.python.org/pypi/collective.carousel

also it would be a good idea to put a text file inside the Collective SVN to help people trying to update their installations.

best regards

**Comment by mishunov** [comment]
Updated the main links on pypi and plone.org. Thanks for pointing this out. Concerning the text file in SVN, doesn't really make sense — buildouts will get it silently and ppl will not even know that the package is not really in their buildout. If there is no package at all on SVN, then buildout will tell about this and will force developers to look at the pages on pypi and plone.org with the updated links.

**Comment by hvelarde** [comment]
I was thinking on humans looking for the code ;-) thanks!
