### ISSUE TITLE
Effects on Products.PloneSlimbox and collective.prettyphoto

### ISSUE THREAD

**Issue by jmce** [collective/collective.carousel#3]
In a Plone 3.3.6 site with collective.carousel (1.4) already installed, I tried installing/using collective.prettyphoto (0.4.3) but this failed to work: in cases where a lightbox was supposed to show up, the browser simply showed the image which would be shown in the lightbox. Removed collective.prettyphoto, installed Products.PloneSlimbox (0.7.1) and got the same problem: no lightbox showing up when it should, only the image which should first go inside it.

After a few tests both in the original site and in another (freshly created) 3.3.6 site, I found out that both collective.prettyphoto and Products.PloneSlimbox work nicely (even if both installed) if they are installed _before_ collective.carousel.

I am not sure if this is the best place to report the above, since I don't know exactly what is causing it.  In any case, maybe it occurs via specific script ordering in the portal_javascripts registry? (since this depends on the order in which products are installed; but I haven't tested reordering the scripts 'manually' after installation).

I haven't yet used collective.carousel itself after installing, so for now I can't report any effects on it.

**Comment by mishunov** [comment]
Let's discuss this if this is still the case, but this issue is way too old to deal with it now.
