### ISSUE TITLE
moving to github.com/collective

### ISSUE THREAD

**Issue by thet** [collective/collective.carousel#4]
@mishunov : what ab out moving this project to github.com/collective, so that it becomes better community-maintainable?

**Comment by mishunov** [comment]
@thet I don't have experience with moving packages in a sane way. Do you feel like helping out? I could give you admin rights for this package so that you could manage this, since I have no time to do this myself. I would appreciate your help.

**Comment by thet** [comment]
@mishunov i'm glad to help out :)

but it's quite easy - in the repo admin screen, you have to "transfer" the ownership to "collective".

and then the excellent collective.carousel becomes again big momentum!

**Comment by mishunov** [comment]
thanks @thet! That was easy indeed. Done. Hope somebody will take over and will maintain the beast further.

**Comment by mishunov** [comment]
Seems like I can't resolve issues now. So, somebody needs to take care of this as well :-P

**Comment by mishunov** [comment]
Hmm, I also have no read rights. Sucks. But, ok with my commit history recently, I guess

**Comment by thet** [comment]
@mishunov cool, already on collective! no read rights, where? and you mean, you cannot close this issue?

regarding maintainance, i think it also can be community maintained. we will use collective.carousel for a current project and there i can do some maintainance. i also could do a release on pypi if you want to add me there (user: thet).

**Comment by mishunov** [comment]
Ha, now I can close the issue. Then this is what I am doing :) I have also added you as the Maintainer for the package on pypi, @thet. Thanks.

**Comment by thet** [comment]
@mishunov, thanks!
